### ISSUE TITLE
Google OpenID login neveikia

### ISSUE THREAD

**Issue by anzi** [sirex/atviriduomenys.lt#2]
http://ad.sirex.lt/accounts/openid/login/?openid=https%3A%2F%2Fwww.google.com%2Faccounts%2Fo8%2Fid
OpenID auth request contains an unregistered domain: http://ad.sirex.lt/
Learn more
That’s all we know.

**Comment by sirex** [comment]
Ačiū. Žinojau, kad Google planuoja nutraukti OpenID palaikymą, bet nesitikėjau, kad tai atsitiks taip greitai. Numigravau prie OAuth, turėtų veikti.

**Comment by anzi** [comment]
data tarsi buvo anonsuota
https://developers.google.com/+/api/auth-migration


***
širdingai
Andrius Žilėnas | andrius.zilenas@gmail.com | +370(624)41862 | Skype:
andrius.z

2015-05-18 15:59 GMT+03:00 sirex <notifications@github.com>:
