### ISSUE TITLE
Mozilla Personas login 

### ISSUE THREAD

**Issue by andzi** [sirex/atviriduomenys.lt#3]
atrodo ir šis neveikia, 
https://login.persona.org/about
http://ad.sirex.lt/accounts/persona/login/
Social Network Login Failure
An error occurred while attempting to login via your social network account.
p.s.
blogai, kad vartotojo paskyroje nėra asocijuotų OpenID valdymo, nesimato iš kokio ID prisijungta

**Comment by sirex** [comment]
>  blogai, kad vartotojo paskyroje nėra asocijuotų OpenID valdymo, nesimato iš kokio ID prisijungta

Taip, reikėtų kada nors tai padaryti.

**Comment by anzi** [comment]
gal yra gatavų?
p.s.
o tu čia nusprendei CKAN'ą perrašyti?


***

2015-05-19 10:34 GMT+03:00 sirex <notifications@github.com>:

**Comment by sirex** [comment]
> gal yra gatavų?

Taip, [django-allauth](https://github.com/pennersr/django-allauth), kurį naudoju turi tokią galimybę, tačiau reikia ją integruoti į svetainę, parašyti šablonus ir pan.

> o tu čia nusprendei CKAN'ą perrašyti?

CKAN yra didelis ir turi daug dalykų, kurių man nereikia, o tuo pačiu neturi elementarių priemonių, kurių man reikia. Be to, jis parašytas ant Pylons karkaso, kuris jau kelis metus nebevystomas. Žodžiu, funkcionalumui, kurį norėjau įgyvendinti atviriduomenys.lt svetainėje CKAN labiau trukdė, nei padėjo, todėl nusprendžiau jo atsisakyti.
